research:
  description: >
    1. Collect the latest news for {topic} from reliable financial sources.
    2. Gather recent press releases related to {topic}.
    3. Retrieve the latest market analyses for {topic} stock and its industry.
    4. Identify key events that could impact the stock's value (e.g., earnings reports, mergers, regulatory changes).
    5. Summarize the findings, highlighting significant trends, market sentiment shifts, and analysts' opinions.
    6. Ensure that any stock ticker associated with {topic} is included in the report.
    
    If additional data is needed, do NOT provide a final answer immediately. Instead, first request the necessary information from available tools.  
    Once all relevant data is collected, format the final response as a structured summary.

    Always use the latest stock data. Do not hallucinate.

  expected_output: >
    A structured report summarizing:
    - Recent news and press releases affecting {topic}.
    - Key market trends and industry shifts.
    - Major analyst opinions and sentiment analysis.
    - Significant upcoming events impacting stock value.
    - Clear mention of the stock ticker for {topic}.

  agent: research_analyst

financial_analysis:
  description: >
    1. Retrieve stock data (open, high, low, close, volume) from **Yahoo Finance**.
    2. Fetch fundamental metrics (P/E ratio, EPS, market cap, etc.) from **Yahoo Finance**. 
    3. Compare financial health indicators with industry benchmarks.
    4. Generate insights on stock performance, valuation, and risk factors.
    5. Provide a final structured financial analysis report, ensuring that relevant stock data is included.

    If you need to perform an action, do NOT provide a final answer immediately. First, request information from the available tools.
    Once you have the necessary information, format your final response in a structured summary.

    Always use the latest stock data. Do not hallucinate.
    
  expected_output: >
    A structured financial analysis report containing:
      - Stock performance (historical trends, using Alpha Vantage or Yahoo Finance as needed)
      - Key valuation metrics (P/E, EPS, market cap, sourced from Yahoo Finance)
      - Profitability & financial health indicators
      - Industry benchmark comparison
      - Final insights and recommendations based on the available data
    
  agent: financial_analyst

recommend:
  description: >
    Combine the findings from the research and financial analysis to create a detailed investment recommendation for {topic}. Consider both qualitative and quantitative data, including market sentiment, financial health, and insights from SEC filings. Ensure that the recommendation includes a summary of upcoming events, insider activity, and risks.

    Generate visualizations (e.g., stock price trends, moving averages, volume trends) to support the recommendation.

    If you need to perform an action, do NOT provide a final answer immediately. First, request information from the available tools.
    Once you have the necessary information, format your final response in a structured summary. 

    Always use the latest stock data. Do not hallucinate.
    
  expected_output: >
    A full, detailed investment recommendation report for {topic}. The recommendation should cover the stock's strengths and weaknesses, investment strategy, and support its stance with data from all previous analyses. Include sections on upcoming events (like earnings), insider trading, and any significant risks or opportunities.
    Have the final section of the report clearly state the recommendation (buy, sell, hold) and provide a brief rationale for the decision.
    Include visualizations (e.g., stock price trends, moving averages, volume trends) to support the recommendation.
  agent: investment_advisor
